Refactor to add new Elasticsearch API Client
craftercms/search pull request #267
Opened 2022-01-24 22:59 UTC by jdrossl

https://github.com/craftercms/craftercms/issues/5210

2022-01-27 15:49 UTC, avasquez614 approved these changes

2022-01-27 15:56 UTC, sumerjabri requested changes
Please also fix SonaType Lift issues.

2022-01-27 15:56 UTC, sumerjabri commented on crafter-search-elasticsearch/src/main/java/org/craftercms/search/elasticsearch/client/ElasticsearchClientWrapper.java
> + * Copyright (C) 2007-2020 Crafter Software Corporation. All Rights Reserved.
Please update the copyright year.

2022-01-27 15:56 UTC, sumerjabri commented on crafter-search-elasticsearch/src/main/java/org/craftercms/search/elasticsearch/impl/client/AbstractElasticsearchClientWrapper.java
> + * Copyright (C) 2007-2020 Crafter Software Corporation. All Rights Reserved.
2022

2022-01-27 15:56 UTC, sumerjabri commented on crafter-search-elasticsearch/src/main/java/org/craftercms/search/elasticsearch/spring/RestHighLevelClientFactory.java
> + * Copyright (C) 2007-2020 Crafter Software Corporation. All Rights Reserved.
2022

2022-01-31 19:52 UTC, sumerjabri approved these changes

2022-01-31 19:54 UTC, merged